// =========================================================
// CREVIO PROJECT CREATE JS
// =========================================================
const form=document.getElementById('projectForm');const submitBtn=document.getElementById('submitBtn');const messageEl=document.getElementById('formMessage');
function getToken(){const t=localStorage.getItem('crevio_token');if(!t){window.location.href='/admin/pages/login.html';return null}return t}
document.getElementById('logoutButton')?.addEventListener('click',()=>{localStorage.removeItem('crevio_token');localStorage.removeItem('crevio_user');window.location.href='/admin/pages/login.html'});
const themeToggle=document.getElementById('themeToggle');if(themeToggle){const saved=localStorage.getItem('crevio_theme')||'dark';document.documentElement.setAttribute('data-theme',saved);themeToggle.addEventListener('click',()=>{const c=document.documentElement.getAttribute('data-theme');const n=c==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',n);localStorage.setItem('crevio_theme',n);if(typeof lucide!=='undefined')lucide.createIcons()})}
const mobileToggle=document.getElementById('mobileToggle');const sidebar=document.getElementById('sidebar');const overlay=document.getElementById('sidebarOverlay');if(mobileToggle&&sidebar&&overlay){mobileToggle.addEventListener('click',()=>{sidebar.classList.toggle('open');overlay.classList.toggle('open')});overlay.addEventListener('click',()=>{sidebar.classList.remove('open');overlay.classList.remove('open')})}
const userData=localStorage.getItem('crevio_user');if(userData){try{const u=JSON.parse(userData);const a=document.getElementById('userAvatar');const nd=document.getElementById('userNameDisplay');if(a&&u.display_name)a.textContent=u.display_name.charAt(0).toUpperCase();if(nd&&u.display_name)nd.textContent=u.display_name}catch(e){console.error(e)}}
function showMessage(t,type='success'){messageEl.style.display='block';messageEl.textContent=t;messageEl.className='form-message '+type}
function hideMessage(){messageEl.style.display='none'}
form.addEventListener('submit',async(e)=>{e.preventDefault();const token=getToken();if(!token)return;const data={title:document.getElementById('title').value.trim(),description:document.getElementById('description').value.trim(),category:document.getElementById('category').value.trim(),thumbnail_url:document.getElementById('thumbnail_url').value.trim(),project_url:document.getElementById('project_url').value.trim(),client_name:document.getElementById('client_name').value.trim(),year:parseInt(document.getElementById('year').value)||null};if(!data.title){showMessage('Project title is required.','error');return}submitBtn.disabled=true;submitBtn.textContent='Creating...';hideMessage();try{const res=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(data)});const result=await res.json();if(!res.ok||!result.success)throw new Error(result.message||'Create failed.');showMessage('Project created successfully!','success');setTimeout(()=>{window.location.href='/dashboard/pages/projects.html'},1000)}catch(err){console.error('Create error:',err);showMessage(err.message||'Unable to create project.','error');submitBtn.disabled=false;submitBtn.textContent='Create Project'}});
